baseurl = "http://callmeradical.github.io"
languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
author = "Lars Cromley"
title = "Lars Cromley"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[index]
  category = "categories"
  tag = "tags"

[Params]
  description = "Technologist, evangelist, and all around nerd. These thoughts are my own and do not reflect that of my employer."
  AuthorName = "Lars Cromley"
  github = "callmeradical"
  twitter = "callmeradical"
  linkedin = "callmeradical"
  disqus = "callmeradical"
  email = "lars@callmeradical.com"
  about = "/pages/about"
  cover = "/images/background.jpg"
  logo = "/images/logo-1.jpg"
  
