baseurl = "http://cromleylabs.com"
languageCode = "en"
title = "Lars Cromley"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/callmeradical\">Lars Cromley</a> 2017"
disqusShortname = "callmeradical"
googleAnalytics = "UA-68276982-1"

Paginate = 10
PaginatePath = "content/post/"
[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "/page/about"
fa_icon = "fa-id-badge"

[[params.social]]
url = "https://github.com/callmeradical"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/callmeradical"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

