baseurl = "http://callmeradical.com"
languageCode = "en-us"
title = "Lars Cromley"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Lars"
  github = "callmeradical"
  twitter = "callmeradical"
  email = "lars@callmeradical.com"
  description = "Technologist, evangelist, and all around nerd. These thoughts are my own and do not reflect that of my employer."
  linkedin = "larscromley"
  cover = "/images/bg.jpg"
  logo = "/images/logo.jpg"
