baseurl = "http://callmeradical.com"
languageCode = "en"
title = "Lars Cromley"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/callmeradical\">Lars Cromley</a> 2016"
disqusShortname = "callmeradical"
googleAnalytics = "UA-68276982-1"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/callmeradical"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/callmeradical"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
