name: CI

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.1
      with:
        hugo-version: '0.55.6'

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir


    - name: Deploy
      run: ./deploy.sh
